name: check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: DeterminateSystems/flake-checker-action@v5

      # Runs checks.<system>.smoke: check-parens in init.el, tangle config.org,
      # byte-compile the result. Defined in flake.nix.
      - name: Check flake
        run: nix flake check --print-build-logs

      - name: Check formatting
        run: nix fmt -- --ci
